global:
  scrape_interval: 60s # How frequently to scrape targets by default.
  scrape_timeout: 10s # How long until a scrape request times out.
  evaluation_interval: 60s # How frequently to evaluate rules.

# A scrape configuration
scrape_configs:
  - job_name: api
    scheme: https
    scrape_interval: 5s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
    - targets: ['public-api.railway.internal']
