global:
  scrape_interval: 5s
  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: "public-api"
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /metrics
    static_configs:
      - targets: ["public-api.railway.internal:8080"]
