global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api'
    scrape_interval: 5s
    static_configs:
      - targets: ['https://public-api-production-769a.up.railway.app/metrics']
