global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: "public-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["https://public-api.railway.internal"]
        labels:
          app: "public-api"
