global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: "public-api"
    scheme: https
    fallback_scrape_protocol: http
    metrics_path: /metrics
    static_configs:
      - targets: ["public-api.railway.internal:443"]
        labels:
          app: "public-api"
